# Development
version: "3.7"

services:
  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ".:/app"
      - "/app/node_modules"
    ports:
      - 55555:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
