version: "3.7"

services:
  carpool-prod:
    container_name: carpool-prod
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "55555:80"
# docker-compose -f docker-compose.prod.yml up -d --build
